---
- name: install reposync
  become: true
  become_user: root
  yum:
    name=yum-utils
    update_cache=yes
    state=latest

- name: install createrepo
  become: true
  become_user: root
  yum:
    name=createrepo
    update_cache=yes
    state=latest
